### PR TITLE
Fix rspec warnings

### PR DESCRIPTION
**Pull request by takiy33**

### CODE REVIEW

**Comment by gazay** [comment]
Great! Thank you! Do you want to take part in developing gon gem?

**Comment by takiy33** [comment]
Yes, I do. I  am interested in gon gem.

**Comment by gazay** [comment]
I've made you collaborator of gon gem =) Welcome! There a lot of issues I don't have time or environment to check, if you help to clean up it – it would be great =)

**Comment by gazay** [comment]
I've created slack channel to discuss issues and features. Please join (send me email to alex.gaziev@gmail.com and I'll send you invite)

**Comment by takiy33** [comment]
Thank you. I sent the email sometime ago.

**Pull request merged**
